### ISSUE TITLE
Interpolation Code Additions 

### ISSUE THREAD

**Issue by carlylagrotta** [The-Burke-Lab/MSI#5]
def interpolation(self,originalValues,newValues, thingBeingInterpolated):   
        #interpolating time historeis to original time history 
        if isinstance(originalValues,pd.DataFrame) and isinstance(newValues,pd.DataFrame):
            tempDfForInterpolation = newValues[thingBeingInterpolated]
            tempListForInterpolation = [tempDfForInterpolation.ix[:,x].values for x in range(tempDfForInterpolation.shape[1])]
            interpolatedData = [np.interp(originalValues['time'].values,newValues['time'].values,tempListForInterpolation[x]) for x in range(len(tempListForInterpolation))]
            interpolatedData = [pd.DataFrame(interpolatedData[x]) for x in range(len(interpolatedData))]
            interpolatedData = pd.concat(interpolatedData, axis=1,ignore_index=True)
            
            
                         # we need to figure out how to change either to ppm or to concentrations 
        # interpolating time histories to experiments 
        elif isinstance(originalValues,pd.DataFrame) and isinstance(newValues,list):
             time = [newValues[x].ix[:,0].values for x in range(len(newValues))]
             interpolatedData = [np.interp(time[x],originalValues['time'].values,originalValues[observable].values) for x,observable in enumerate(thingBeingInterpolated)]
             
             interpolatedData = [pd.DataFrame(interpolatedData[x]) for x in range(len(interpolatedData))]
             interpolatedData = [interpolatedData[x].as_matrix().flatten() for x in range(len(interpolatedData))] 
             interpolatedData = dict(zip(thingBeingInterpolated,interpolatedData))
             
             
        return interpolatedData

**Comment by carlylagrotta** [comment]
def importingExperimentalData(csvFileList):
        experimentalData = [pd.read_csv(csv) for csv in csvFileList] 
        experimentalData = [experimentalData[x].dropna(how='any') for x in range(len(experimentalData))]
        experimentalData = [experimentalData[x].apply(pd.to_numeric, errors = 'coerce').dropna() for x in range(len(experimentalData))]
        
        return experimentalData

**Comment by gammison** [comment]
Done, time interpolation completed.
