### ISSUE TITLE
Sensitivity Calcuation

### ISSUE THREAD

**Issue by carlylagrotta** [The-Burke-Lab/MSI#6]
def sensitivityCalculation(self,originalValues,newValues,thingToFindSensitivtyOf,dk=.01):
    if isinstance(originalValues,pd.DataFrame) and isinstance(newValues,pd.DataFrame):
        newValues.columns = thingToFindSensitivtyOf
        newValues = newValues.applymap(np.log)
        originalValues = originalValues.applymap(np.log)
        sensitivity = (newValues.subtract(originalValues)/dk)
        sensitivityList = [sensitivity.ix[:,idx] for idx in range(sensitivity.shape[1])]
        
        return sensitivityList

**Comment by gammison** [comment]
done
