### ISSUE TITLE
Interpolating things to experimental data 

### ISSUE THREAD

**Issue by carlylagrotta** [The-Burke-Lab/MSI#8]
def interpolation(self,originalValues,newValues, thingBeingInterpolated,p_sens=None):   
        #interpolating time histories to original time history 
        if isinstance(originalValues,pd.DataFrame) and isinstance(newValues,pd.DataFrame):
            tempDfForInterpolation = newValues[thingBeingInterpolated]
            
            tempListForInterpolation = [tempDfForInterpolation.ix[:,x].values for x in range(tempDfForInterpolation.shape[1])]
            interpolatedData = [np.interp(originalValues['time'].values,newValues['time'].values,tempListForInterpolation[x]) for x in range(len(tempListForInterpolation))]
            interpolatedData = [pd.DataFrame(interpolatedData[x]) for x in range(len(interpolatedData))]
            interpolatedData = pd.concat(interpolatedData, axis=1,ignore_index=True)
            interpolatedData.columns = thingBeingInterpolated
            
            
            
        # we need to figure out how to change either to ppm or to concentrations 
        # interpolating time histories to experiments 
        elif isinstance(originalValues,pd.DataFrame) and isinstance(newValues,list):
             time = [newValues[x].ix[:,0].values for x in range(len(newValues))]
             interpolatedData = [np.interp(time[x],originalValues['time'].values,p_sens[observable].values) for x,observable in enumerate(thingBeingInterpolated)]
             
             interpolatedData = [pd.DataFrame(interpolatedData[x]) for x in range(len(interpolatedData))]
             interpolatedData = pd.concat(interpolatedData, axis=1,ignore_index=True)
             #interpolatedData = [interpolatedData[x].as_matrix().flatten() for x in range(len(interpolatedData))] 
             interpolatedData = dict(zip(thingBeingInterpolated,interpolatedData))
             
             
        return interpolatedData

**Comment by gammison** [comment]
problem, can only do one species sensitivity at a time, not all

**Comment by gammison** [comment]
done
